### ISSUE TITLE
How to configure wdio-rerun-service for Cucumber

### ISSUE THREAD

**Issue by Nisim761** [jwplayer/wdio-rerun-service#16]
Hi,
I am trying to follow the instructions on how to configure this service, but it seems like i am missing something. I don't have a file named "wdio.conf.js" in my project and we don't configure "services" array. How \ where i am supposed to configure this service and define the options?

**Comment by mikesalvia** [comment]
Please send over your WDIO configuration wherever it may be placed.

**Comment by esaari** [comment]
Closing since a period of time elapsed with no response. If you’re still having issues  @Nisim761 feel free to reopen and we can try to help you out.
