### ISSUE TITLE
wdio-rerun-service not working with cucumber

### ISSUE THREAD

**Issue by NachiketPawar** [jwplayer/wdio-rerun-service#5]
I am trying wdio-rerun-service with cucumber framework.Following are the logs.
In logs I can see that it has generated rerun.sh file. But looks like it is not getting executed.
I am using latest version of service 0.0.9.
###############################################################################
Execution of 1 spec files started at 2020-09-17T10:31:49.785Z

[0-0] RUNNING in chrome - C:\########\cucumber-boilerplate-master\cucumber-boilerplate-master\src\features\MakeMyTrip2.feature
[0-0] Re-run service is activated. Data directory: ./results/rerun
[0-0] Error in "Test MakeMyTrip Login: Test if user is able to serach hotels on MakeMyTrip portal - MakeMyTrip2 Scenario1: And I click on the element "div.selectHtlCity123""
expect(received).toBeGreaterThanOrEqual(expected)

Expected: >= 1
Received:    0
[0-0] Re-run service is inspecting non-passing scenario.
[0-0] Scenario location: src\features\MakeMyTrip2.feature:9
Scenario tags:
[0-0] FAILED in chrome - C:\############\cucumber-boilerplate-master\cucumber-boilerplate-master\src\features\MakeMyTrip2.feature
Re-run script has been generated @ ./rerun.sh

 "spec" Reporter:
------------------------------------------------------------------
[Chrome 85.0.4183.102 win32 #0-0] Spec: C:\###############\cucumber-boilerplate-master\cucumber-boilerplate-master\src\features\MakeMyTrip2.feature
[Chrome 85.0.4183.102 win32 #0-0] Running: Chrome (v85.0.4183.102) on win32
[Chrome 85.0.4183.102 win32 #0-0] Session ID: 48850ec7-ed94-40db-bbb7-4930b9b48562
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0] Test MakeMyTrip Login
[Chrome 85.0.4183.102 win32 #0-0] As a developer
[Chrome 85.0.4183.102 win32 #0-0] I want to be able to test if user is able to search for hotels Scenario
[Chrome 85.0.4183.102 win32 #0-0] on MakeMyTrip site
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0]     Test if user is able to serach hotels on MakeMyTrip portal - MakeMyTrip2 Scenario1
[Chrome 85.0.4183.102 win32 #0-0]     As a developer
[Chrome 85.0.4183.102 win32 #0-0]     I want to be able to test if user is able to search for hotels Scenario
[Chrome 85.0.4183.102 win32 #0-0]     on MakeMyTrip site
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0]        ✓ Given I open the site "/"
[Chrome 85.0.4183.102 win32 #0-0]        ✓ When I doubleclick on the element "li.menu_Hotels a"
[Chrome 85.0.4183.102 win32 #0-0]        ✖ And I click on the element "div.selectHtlCity123"
[Chrome 85.0.4183.102 win32 #0-0]        - And I wait on element "div[role='combobox'] > .react-autosuggest__input" for 5000ms to exist
[Chrome 85.0.4183.102 win32 #0-0]        - And I set "Pune" to the inputfield "div[role='combobox'] > .react-autosuggest__input"
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0] 2 passing (19.6s)
[Chrome 85.0.4183.102 win32 #0-0] 1 failing
[Chrome 85.0.4183.102 win32 #0-0] 2 skipped
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0] 1) Test if user is able to serach hotels on MakeMyTrip portal - MakeMyTrip2 Scenario1 And I click on the element "div.selectHtlCity123"
[Chrome 85.0.4183.102 win32 #0-0] expect(received).toBeGreaterThanOrEqual(expected)

Expected: >= 1
Received:    0
[Chrome 85.0.4183.102 win32 #0-0] Error: expect(received).toBeGreaterThanOrEqual(expected)
[Chrome 85.0.4183.102 win32 #0-0]
[Chrome 85.0.4183.102 win32 #0-0] Expected: >= 1
[Chrome 85.0.4183.102 win32 #0-0] Received:    0
[Chrome 85.0.4183.102 win32 #0-0]     at _default (C:\#####\cucumber-boilerplate-master\cucumber-boilerplate-master\src\support\lib\/checkIfElementExists.js:27:37)
[Chrome 85.0.4183.102 win32 #0-0]     at World._default (C:\#####\cucumber-boilerplate-master\cucumber-boilerplate-master\src\support\action\/clickElement.js:22:5)
[Chrome 85.0.4183.102 win32 #0-0]     at World.executeSync (C:\#####\cucumber-boilerplate-master\cucumber-boilerplate-master\node_modules\@wdio\sync\build\index.js:5
6:18)
[Chrome 85.0.4183.102 win32 #0-0]     at C:\########\cucumber-boilerplate-master\cucumber-boilerplate-master\node_modules\@wdio\sync\build\index.js:80:70

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:24

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##############################################################################

**Comment by mikesalvia** [comment]
What are the contents of `rerun.sh` that is generated?

**Comment by mikesalvia** [comment]
Also please add your config block for `services`.

**Comment by NachiketPawar** [comment]
Hi,

PFB content of rerun file.
DISABLE_RERUN=true wdio wdio.conf.js  --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9 --spec=src\features\MakeMyTrip2.feature:9

So every time a scenario fails it keeps adding entry in the rerun file. It should clean up content from previous run.

Config Block For services:
services: [[RerunService]]

**Comment by mikesalvia** [comment]
@NachiketPawar You are right, we are making an assumption that the developer is handling their results directory, also in CI/CD we generally wipe a workspace before testing, what we can do is look through all the specs and make a unique list, this should make it a bit more usable.

**Comment by mikesalvia** [comment]
Closing enhancement to come in 1.6.0.
