### ISSUE TITLE
path separators in rerun.sh in windows is incorrect

### ISSUE THREAD

**Issue by johnson-tyl** [jwplayer/wdio-rerun-service#7]
The rerun file created when running on Windows has the wrong path separators for the feature files, it need to have double `\\` or single `/` for it to work in Windows, best would be to just have single `/`

**Comment by mikesalvia** [comment]
@johnson-tyl Can you post a copy of your re-run.sh?

**Comment by mikesalvia** [comment]
I am just about to push up a change to fix this! I will update with PR and let you know when it is released.

**Comment by mikesalvia** [comment]
@johnson-tyl This is fixed in 1.6.0.

**Comment by algoritmus** [comment]
it does not work on windows anyway.....
